# Generated by Django 4.2.7 on 2025-11-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_details',
            field=models.TextField(blank=True, help_text='JSON data for payment gateway details'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('gpay', 'GPay'), ('razorpay', 'Razorpay')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment gateway transaction ID', max_length=100),
        ),
    ]
